name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            extension: ''
          - os: windows-latest
            extension: .exe
          - os: macos-latest
            extension: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --add-data "resources/*:resources" Main.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/Main${{ matrix.extension }}

      - name: List files in dist folder
        run: ls dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/build-ubuntu-latest/Main
            release/build-windows-latest/Main.exe
            release/build-macos-latest/Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
